# Site settings
title: 除10
email: divide10@outlook.com
description: 原来你也在这里
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
